#!/bin/bash

# directories
PWD=`pwd`
DATE=$1
ATR="$PWD/data/actor"
ACT="$PWD/data/acts"
DIS="$PWD/data/display"
MOV="$PWD/data/movie"
SET="$PWD/data/seat"
TYP="$PWD/data/type"
DES="$PWD/${DATE}csvs"

`mkdir $PWD/${DATE}csvs`

# detect parameters
if [ -z "$1" ]; then
    echo "Usage: ./update_no_merge.sh [mmdd-mmdd]"
    echo "data will generated by python and be formated by scripts by date(mmdd-mmdd)"
    exit
else
    echo "Start crawling data ..."
    echo ""
fi

################
## crawl data ##
################

# actor
INFO_PY="$ATR/info.py"
RAW_INFODATA="$ATR/raw_infodata$DATE.txt"
RAWINFO2ACTOR_SH="$ATR/rawinfo2actor.sh"
NAMES="$ATR/names.txt"
HASH_PY="$ATR/hash.py"
ACTOR_DATA="$DES/actor_data$DATE.csv"

# web (info.py)> raw_infodata.txt (rawinfo2actor.sh)> names.txt (hash.py)> actor_data.csv
`python3 $INFO_PY > $RAW_INFODATA`
`chmod 644 $RAW_INFODATA`
`$RAWINFO2ACTOR_SH $RAW_INFODATA $NAMES`
`chmod 644 $NAMES`
`python3 $HASH_PY > $ACTOR_DATA`
`chmod 644 $ACTOR_DATA`
echo "==== actor done ===="


# type
RAW_INFODATA="$ATR/raw_infodata$DATE.txt"
RAWINFO2TYPE_SH="$TYP/rawinfo2type.sh"
TYPE_DATA="$DES/type_data$DATE.csv"

# raw_infodata.txt (rawinfo2type.sh)> type_data.csv
`$RAWINFO2TYPE_SH $RAW_INFODATA $TYPE_DATA`
`chmod 644 $TYPE_DATA`
echo "==== type done ===="


# acts
INFOACT_PY="$ACT/info_act.py"
ACTS_RAWDATA="$ACT/acts_rawdata$DATE.txt"
RAWINFO2ACT_SH="$ACT/rawinfo2act.sh"
ACTS_DATA="$DES/acts_data$DATE.csv"

# web (info_act.py)> acts_rawdata.txt (rawinfo2act.sh)> acts_data.csv
`python3 $INFOACT_PY > $ACTS_RAWDATA`
`chmod 644 $ACTS_RAWDATA`
`$RAWINFO2ACT_SH $ACTS_RAWDATA $ACTS_DATA`
`chmod 644 $ACTS_DATA`
echo "==== acts done ===="


# display
AMBASSA_PY="$DIS/ambassa.py"
DISPLAY_RAWDATA="$DIS/display_rawdata$DATE.txt"
DISPLAYTXT2CSV_SH="$DIS/display_txt2csv.sh"
DISPLAY_DATA="$DES/display_data$DATE.csv"

# web (ambassa.py)> display_rawdata.txt (display_txt2csv.sh)> display_data.csv
`python3 $AMBASSA_PY > $DISPLAY_RAWDATA`
`chmod 644 $DISPLAY_RAWDATA`
`$DISPLAYTXT2CSV_SH $DISPLAY_RAWDATA $DISPLAY_DATA`
`chmod 644 $DISPLAY_DATA`
echo "==== display done ===="


# seat
SEATGENERATE_PY="$SET/seat_generate.py"
SEAT_DATA="$DES/seat_data$DATE.csv"

# (seat_generate.py)> seat.data.csv
`sed -i "s/date = .*/date = \"$DATE\"/g" $SEATGENERATE_PY`
`python3 $SEATGENERATE_PY > $SEAT_DATA`
`chmod 644 $SEAT_DATA`
echo "==== seat done ===="

