#!/bin/bash

# directories
PWD=`pwd`
DATE=$1
ATR="$PWD/data/actor"
ACT="$PWD/data/acts"
DIS="$PWD/data/display"
MOV="$PWD/data/movie"
SET="$PWD/data/seat"
TYP="$PWD/data/type"

# detect parameters
if [ -z "$1" ]; then
    echo "Usage: ./update_all_data.sh [mmdd-mmdd]"
    echo "data will generated by python and be formated by scripts by date(mmdd-mmdd)"
    exit
else
    echo "Start crawling data ..."
    echo ""
fi

################
## crawl data ##
################

# actor
INFO_PY="$ATR/info.py"
RAW_INFODATA="$ATR/raw_infodata$DATE.txt"
RAWINFO2ACTOR_SH="$ATR/rawinfo2actor.sh"
NAMES="$ATR/names.txt"
HASH_PY="$ATR/hash.py"
ACTOR_DATA="$ATR/actor_data$DATE.csv"

# web (info.py)> raw_infodata.txt (rawinfo2actor.sh)> names.txt (hash.py)> actor_data.csv
`python3 $INFO_PY > $RAW_INFODATA`
`chmod 644 $RAW_INFODATA`
`$RAWINFO2ACTOR_SH $RAW_INFODATA $NAMES`
`chmod 644 $NAMES`
`python3 $HASH_PY > $ACTOR_DATA`
`chmod 644 $ACTOR_DATA`
echo "==== actor done ===="


# type
RAW_INFODATA="$ATR/raw_infodata$DATE.txt"
RAWINFO2TYPE_SH="$TYP/rawinfo2type.sh"
TYPE_DATA="$TYP/type_data$DATE.csv"

# raw_infodata.txt (rawinfo2type.sh)> type_data.csv
`$RAWINFO2TYPE_SH $RAW_INFODATA $TYPE_DATA`
`chmod 644 $TYPE_DATA`
echo "==== type done ===="


# acts
INFOACT_PY="$ACT/info_act.py"
ACTS_RAWDATA="$ACT/acts_rawdata$DATE.txt"
RAWINFO2ACT_SH="$ACT/rawinfo2act.sh"
ACTS_DATA="$ACT/acts_data$DATE.csv"

# web (info_act.py)> acts_rawdata.txt (rawinfo2act.sh)> acts_data.csv
`python3 $INFOACT_PY > $ACTS_RAWDATA`
`chmod 644 $ACTS_RAWDATA`
`$RAWINFO2ACT_SH $ACTS_RAWDATA $ACTS_DATA`
`chmod 644 $ACTS_DATA`
echo "==== acts done ===="


# display
AMBASSA_PY="$DIS/ambassa.py"
DISPLAY_RAWDATA="$DIS/display_rawdata$DATE.txt"
DISPLAYTXT2CSV_SH="$DIS/display_txt2csv.sh"
DISPLAY_DATA="$DIS/display_data$DATE.csv"

# web (ambassa.py)> display_rawdata.txt (display_txt2csv.sh)> display_data.csv
`python3 $AMBASSA_PY > $DISPLAY_RAWDATA`
`chmod 644 $DISPLAY_RAWDATA`
`$DISPLAYTXT2CSV_SH $DISPLAY_RAWDATA $DISPLAY_DATA`
`chmod 644 $DISPLAY_DATA`
echo "==== display done ===="


# movie
DISPLAY_RAWDATA="$DIS/display_rawdata$DATE.txt"
RAWDISPLAY2MOVIE_SH="$MOV/rawdisplay2movie.sh"
MOVIE_DATA="$MOV/movie_data$DATE.csv"

# display_rawdata.txt (rawdisplay2movie.sh)> movie_data.csv
`$RAWDISPLAY2MOVIE_SH $DISPLAY_RAWDATA $MOVIE_DATA`
`chmod 644 $MOVIE_DATA`
echo "==== movie done ===="


# seat
SEATGENERATE_PY="$SET/seat_generate.py"
SEAT_DATA="$SET/seat_data.csv"

# (seat_generate.py)> seat.data.csv
`python3 $SEATGENERATE_PY > $SEAT_DATA`
`chmod 644 $SEAT_DATA`
echo "==== seat done ===="


################
## merge data ##
################

echo "Start merging data ..."
echo ""

# merge
MERGE_SH="$PWD/data/merge.sh"
ACTOR_MASTER="$ATR/actor_master.csv"
ACTS_MASTER="$ACT/acts_master.csv"
DISPLAY_MASTER="$DIS/display_master.csv"
MOVIE_MASTER="$MOV/movie_master.csv"
TYPE_MASTER="$TYP/type_master.csv"

# actor
`$MERGE_SH $ACTOR_MASTER $ACTOR_DATA`
echo "==== actor done ===="

# acts
`$MERGE_SH $ACTS_MASTER $ACTS_DATA`
echo "==== acts done ===="

# display
`$MERGE_SH $DISPLAY_MASTER $DISPLAY_DATA`
echo "==== display done ===="

# movie
`$MERGE_SH $MOVIE_MASTER $MOVIE_DATA`
echo "==== movie done ===="

# type
`$MERGE_SH $TYPE_MASTER $TYPE_DATA`
echo "==== type done ===="

